### ISSUE TITLE
Azure Standard_A1 server

### ISSUE THREAD

**Issue by beautyfree** [oraclesorg/test-templates#11]
In your config Standard A1 servers are listed. Do you use them when deploying a nodes?

![image](https://user-images.githubusercontent.com/656531/28969077-b431d8cc-792b-11e7-9f30-8842adc22e60.png)
1 core with 2.2Ghz at the nodes

The load increases with the number of blocks, then the parity was updated and the generation of blocks started from scratch. Within a few days the load on the processor again increased and the CPU did not suffice to generate new blocks.

As a result, the network goes into desynchronous and the nodes "fall off"

**Comment by phahulin** [comment]
We don't observe this behaviour on our nodes. There maybe occasional spikes of CPU but not a constant load.

Few questions to start with:
1. How many nodes do you have in total? How many blocks?
2. Do you observe this on each node?
3. Could you connect to a node and find out which process consumes that much CPU (using top or installing htop)?
4. You write that
> then the parity was updated

does it mean you didn't use our new templates and updated docker image instead? We've not tested new version from docker, as we decided to use parity binary. More importantly, there are changes needed to be made when upgrading from 1.6 to 1.7, both in node configuration file (node.toml) and in chain spec file (contract abi is changed in 1.7). This also means that you can't use miner's keys generated previously.
