### ISSUE TITLE
Why `--ui-no-validation`

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/test-templates#12]
For security reasons, I don't see why mining node should have this flag.
https://github.com/oraclesorg/test-templates/blob/AlphaTestTestNet/TestTestNet/mining-node/install.sh#L276

Everybody who wants to interact with OraclesPoA, should setup their own eth node.

**Comment by phahulin** [comment]
Thanks for noting, resolved in https://github.com/oraclesorg/test-templates/commit/e2eee1b0c95076fec0494819793c66a199ab3f0e
