### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by micwebnet** [oraclesorg/test-templates#17]
Followed https://www.youtube.com/watch?v=LeYGKyMqSzM. Deployed from AlphaTestTestNet to Azure, into a new VM. Deployment succeeded, but my node isn't showing up under http://testnet.oracles.org:3000/. 

Thanks,  Michael

**Comment by phahulin** [comment]
Could you tell your node's IP address?

**Comment by micwebnet** [comment]
Node IP: 13.92.88.138

I'm seeing this: 

mmilirud@MyUbuntuVM:~$ sudo journalctl -u oracles-parity
-- Logs begin at Wed 2017-10-04 19:46:31 UTC, end at Wed 2017-10-04 19:54:02 UTC. --
Oct 04 19:46:41 MyUbuntuVM systemd[1]: Started oracles parity service.
Oct 04 19:46:45 MyUbuntuVM parity[1200]: Loading config file from node.toml
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  Starting Parity/v1.7.0-beta-5f2cabd-2017
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  Keys path parity/keys/OraclesPoA
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  DB path parity/chains/OraclesPoA/db/25bd
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  Path to dapps parity/dapps
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  State DB configuration: fast
Oct 04 19:46:48 MyUbuntuVM parity[1200]: 2017-10-04 19:46:48 UTC main INFO parity::run  Operating mode: active
**Oct 04 19:46:49 MyUbuntuVM parity[1200]: No valid password to unlock account fe1a…0d89. Make sure valid password is present in files passed using `--password` or in the configuration file.
Oct 04 19:46:49 MyUbuntuVM systemd[1]: oracles-parity.service: Main process exited, code=exited, status=1/FAILURE**
Oct 04 19:46:49 MyUbuntuVM systemd[1]: oracles-parity.service: Unit entered failed state.
Oct 04 19:46:49 MyUbuntuVM systemd[1]: oracles-parity.service: Failed with result 'exit-code'.
Oct 04 19:46:49 MyUbuntuVM systemd[1]: oracles-parity.service: Service hold-off time over, scheduling restart.
Oct 04 19:46:49 MyUbuntuVM systemd[1]: Stopped oracles parity service.

**Comment by micwebnet** [comment]
Looking at the password, I may have used j instead of J. Fonts used in the Ceremony app make it hard to distinguish. Recommend using clear fixed-size font, like courier for the address and password in UX.

Where/how do I update the password in the VM?

**Comment by phahulin** [comment]
`node.pwd` file should be in your home directory on the VM, please correct the password there, then restart parity
```
sudo systemctl restart oracles-parity
```
and netstats service
```
pm2 restart all
```

**Comment by micwebnet** [comment]
Thanks! Updated j to J with nano editor in node.pwd. Then ran commands, as listed above. 

Per content of sudo journalctl -u oracles-parity looks like it's booting. It'd be nice to be able to track progress of node booting.

**Comment by micwebnet** [comment]
Node showed up after about 5 minutes. 

Thanks!
