### ISSUE TITLE
Suggestion in template's UI/UX

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#21]
Please review and implement suggestions by Jeff Flowers
https://docs.google.com/document/d/e/2PACX-1vTiDlkMZAwpSrXghD2ZqWV8NQqHqsW-vChOZmxTM1-mi3gUf2SCPQkg8pFeZkOFwQz9nMmT7INya3d0/pub

**Comment by phahulin** [comment]
Implemented for mining nodes in the upcoming branch (dev-mainnet)
http://take.ms/ppckz
