### ISSUE TITLE
High consistent CPU usage 

### ISSUE THREAD

**Issue by micwebnet** [oraclesorg/test-templates#23]
Seeing very high consistent CPU usage on my VM node:

![image](https://user-images.githubusercontent.com/29300459/32138110-4fba11b2-bbe2-11e7-91db-64b317abde7f.png)

**Comment by igorbarinov** [comment]
This problem is fixed in Parity 1.8

**Comment by igorbarinov** [comment]
In the new testnet we'll not have the problem
