### ISSUE TITLE
(Feature) Add nginx to boonode in Sokol configuration

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#24]
Rationale:
- nginx allows to proxy RPC calls using https on 443 port
- proxying RPC using https allows  connecting to MEW (myethereum wallet) and other services which require https

we can use nginx setup from kovan 
https://github.com/kovan-testnet/rpc-node-setup

private key and certificate chain will be provided in a UI of azure while deploying the VM

**Comment by igorbarinov** [comment]
UPD

Let's install a self-signed certificate. Boot node will be cloaked by Cloudflare

**Comment by phahulin** [comment]
It's done
