### ISSUE TITLE
Auto install security updates for docker host/docker guest

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#5]
For Docker guest:
https://stackoverflow.com/a/26543374/1268964

The same can be used for the docker host

**Comment by phahulin** [comment]
Done in https://github.com/oraclesorg/test-templates/commit/5f5b4c6f056801cc5d4fd6665986a6b1e8bd2f8c

**Comment by igorbarinov** [comment]
Let's clone this itech/docker-run container to our docker acc?

**Comment by phahulin** [comment]
Done in https://github.com/oraclesorg/test-templates/commit/465b36786bdc777d972f14ae59651643f31b1b95 and https://github.com/oraclesorg/test-templates/commit/2c8b54b37fb57c6e2c4b1983b1adf3a941e62f18
