### ISSUE TITLE
Add Ethereum Network Intelligence API

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#7]
In installer of Parity (`curl https://get.parity.io -Lk`) there is a block about installing  netstats

```		cd $HOME

		[ ! -d "www" ] && git clone https://github.com/cubedro/eth-net-intelligence-api netstats
		oldpwd= $(pwd)
		cd netstats
		sudo npm install
		sudo npm install pm2 -g

		cat > app.json << EOL
```
Let's install the main node on the bootnode for the testnet and connect from each mining node. A secret will be one more manual field when a miner runs the template.

**Comment by igorbarinov** [comment]
Yes, let's install it on bootnode.

**Comment by igorbarinov** [comment]
If would be good to provide a custom name for each node, e.g. Full name of a notary to show it on the stats page. Let's add it to the template

**Comment by phahulin** [comment]
This is done
