### ISSUE TITLE
Add --force-sealing to parity client launch

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/test-templates#8]
```The consensus can be ran with --force-sealing which ensures that blocks are produced even if there are no transactions. This is necessary for fault tolerance described.```

https://github.com/paritytech/parity/wiki/Aura

**Comment by phahulin** [comment]
Added in https://github.com/oraclesorg/test-templates/commit/b220e9c1a978e21a2cc3ec5058d5c017084a80a5 
Remember to double check parity version (1.6.x, not 1.7.x)
