### ISSUE TITLE
Rights and folders

### ISSUE THREAD

**Issue by phahulin** [oraclesorg/test-templates#9]
By default azure downloads and runs installation script in `/var/lib/waagent/custom-script/download/0/` under `root`.
By default `root` doesn't have a password, i.e. you can run `sudo any-command` without password.

1. Should we move all necessary files to `/home/$ADMIN_USERNAME` and change files ownership to `$ADMIN_USERNAME`?
2. Should we make a password for sudo and ask it in cloud UI?
3. Should we run docker as [non-root that is still equivalent to root](https://docs.docker.com/engine/installation/linux/linux-postinstall/)?

**Comment by igorbarinov** [comment]
1. It will be easier for validators to move their files from /home when they will upgrade or migrate instances. It makes sense to move data
2. Don't see a reason to do so. The admin user equals to root.
3. Let's run as a non-root user.

**Comment by phahulin** [comment]
These are all resolved now as we've switched to parity binary and start all services as non-root user.
